services:
  postgres_db_message:
    image: postgres:15-alpine
    container_name: postgres_db_message
    environment:
       POSTGRES_USER: root
       POSTGRES_PASSWORD: root
       POSTGRES_DB: insider-message
    ports:
      - "5455:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/1-seed.sql
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: message-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
  message-service:
    build: .
    container_name: message-service
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://root:root@postgres_db_message:5432/insider-message?sslmode=disable
      - REDIS_ADDR=redis:6379 
      - REDIS_PASSWORD=""
      - REDIS_DB=0
    depends_on:
      - redis
      - postgres_db_message
    restart: on-failure:10

volumes:
  postgres-data:
  redis-data: